// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuHW8LEhdaDePvJ29TL4Qr2gv-Fx6y-A',
    appId: '1:654822826830:web:55c63e2b34e1fa6476b41f',
    messagingSenderId: '654822826830',
    projectId: 'clone-4bbeb',
    authDomain: 'clone-4bbeb.firebaseapp.com',
    storageBucket: 'clone-4bbeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagz7lpxAEb6EUewQ5yTt0eUQVpgOL54s',
    appId: '1:654822826830:android:a5e9aa93c5b65d6176b41f',
    messagingSenderId: '654822826830',
    projectId: 'clone-4bbeb',
    storageBucket: 'clone-4bbeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOjoI_spTBfjpa84LHcXaBrvNZR_6rU_Y',
    appId: '1:654822826830:ios:07362cc6bdc2807076b41f',
    messagingSenderId: '654822826830',
    projectId: 'clone-4bbeb',
    storageBucket: 'clone-4bbeb.appspot.com',
    iosBundleId: 'farizaaa.app.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOjoI_spTBfjpa84LHcXaBrvNZR_6rU_Y',
    appId: '1:654822826830:ios:78c8e163c8cdb1f976b41f',
    messagingSenderId: '654822826830',
    projectId: 'clone-4bbeb',
    storageBucket: 'clone-4bbeb.appspot.com',
    iosBundleId: 'farizaaa.app.amazonClone.RunnerTests',
  );
}
